/* =========================================================================
   KANA — tableaux et exercices.
   Format d'un mot : ["écriture en kana", "rōmaji", "sens en français"],
   Dans le rōmaji, une lettre entre accolades {} s'affiche en gris : elle ne se
   prononce pas telle quelle, elle allonge la voyelle précédente (sensei = sensé).
   niveau2 et niveau3 ne contiennent aucun kana à accent : ceux-ci ont leur
   propre niveau 4, avec les mots qui les utilisent.
   ========================================================================= */

const KANA = {
  hira: {
    nom: "Hiragana",
    yoon: [
      ["きゃ","kya"],
      ["きゅ","kyu"],
      ["きょ","kyo"],
      ["しゃ","sha"],
      ["しゅ","shu"],
      ["しょ","sho"],
      ["ちゃ","cha"],
      ["ちゅ","chu"],
      ["ちょ","cho"],
      ["にゃ","nya"],
      ["にゅ","nyu"],
      ["にょ","nyo"],
      ["ひゃ","hya"],
      ["ひゅ","hyu"],
      ["ひょ","hyo"],
      ["みゃ","mya"],
      ["みゅ","myu"],
      ["みょ","myo"],
      ["りゃ","rya"],
      ["りゅ","ryu"],
      ["りょ","ryo"],
      ["ぎゃ","gya"],
      ["ぎゅ","gyu"],
      ["ぎょ","gyo"],
      ["じゃ","ja"],
      ["じゅ","ju"],
      ["じょ","jo"],
      ["びゃ","bya"],
      ["びゅ","byu"],
      ["びょ","byo"],
      ["ぴゃ","pya"],
      ["ぴゅ","pyu"],
      ["ぴょ","pyo"]
    ],
    base: [
      ["あ","a"],
      ["い","i"],
      ["う","u"],
      ["え","e"],
      ["お","o"],
      ["か","ka"],
      ["き","ki"],
      ["く","ku"],
      ["け","ke"],
      ["こ","ko"],
      ["さ","sa"],
      ["し","shi"],
      ["す","su"],
      ["せ","se"],
      ["そ","so"],
      ["た","ta"],
      ["ち","chi"],
      ["つ","tsu"],
      ["て","te"],
      ["と","to"],
      ["な","na"],
      ["に","ni"],
      ["ぬ","nu"],
      ["ね","ne"],
      ["の","no"],
      ["は","ha"],
      ["ひ","hi"],
      ["ふ","fu"],
      ["へ","he"],
      ["ほ","ho"],
      ["ま","ma"],
      ["み","mi"],
      ["む","mu"],
      ["め","me"],
      ["も","mo"],
      ["や","ya"],
      ["ゆ","yu"],
      ["よ","yo"],
      ["ら","ra"],
      ["り","ri"],
      ["る","ru"],
      ["れ","re"],
      ["ろ","ro"],
      ["わ","wa"],
      ["を","wo"],
      ["ん","n"]
    ],
    dakuten: [
      ["が","ga"],
      ["ぎ","gi"],
      ["ぐ","gu"],
      ["げ","ge"],
      ["ご","go"],
      ["ざ","za"],
      ["じ","ji"],
      ["ず","zu"],
      ["ぜ","ze"],
      ["ぞ","zo"],
      ["だ","da"],
      ["ぢ","ji"],
      ["づ","zu"],
      ["で","de"],
      ["ど","do"],
      ["ば","ba"],
      ["び","bi"],
      ["ぶ","bu"],
      ["べ","be"],
      ["ぼ","bo"],
      ["ぱ","pa"],
      ["ぴ","pi"],
      ["ぷ","pu"],
      ["ぺ","pe"],
      ["ぽ","po"]
    ],
    niveau2: [
      ["ねこ","neko","le chat"],
      ["いぬ","inu","le chien"],
      ["やま","yama","la montagne"],
      ["うみ","umi","la mer"],
      ["そら","sora","le ciel"],
      ["とり","tori","l'oiseau"],
      ["ほし","hoshi","l'étoile"],
      ["かわ","kawa","la rivière"],
      ["ゆき","yuki","la neige"],
      ["あめ","ame","la pluie"],
      ["はし","hashi","le pont"],
      ["くつ","kutsu","les chaussures"],
      ["はな","hana","la fleur"],
      ["つき","tsuki","la lune"],
      ["ひと","hito","la personne"],
      ["いえ","ie","la maison"],
      ["くち","kuchi","la bouche"],
      ["ふね","fune","le bateau"],
      ["えき","eki","la gare"],
      ["あき","aki","l'automne"],
      ["なつ","natsu","l'été"],
      ["ふゆ","fuyu","l'hiver"],
      ["はる","haru","le printemps"],
      ["みみ","mimi","les oreilles"],
      ["うた","uta","la chanson"],
      ["きた","kita","le nord"],
      ["にく","niku","la viande"],
      ["ゆめ","yume","le rêve"],
      ["いし","ishi","la pierre"],
      ["かさ","kasa","le parapluie"],
      ["にわ","niwa","le jardin"],
      ["あし","ashi","la jambe"],
      ["かみ","kami","le papier"],
      ["ちち","chichi","mon père"],
      ["はは","haha","ma mère"],
      ["やさ","yasa","la douceur"]
    ],
    niveau3: [
      ["さくら","sakura","les cerisiers"],
      ["くるま","kuruma","la voiture"],
      ["つくえ","tsukue","le bureau"],
      ["なまえ","namae","le nom"],
      ["おかね","okane","l'argent"],
      ["せんせい","sense{i}","le professeur"],
      ["やさい","yasai","les légumes"],
      ["ちかてつ","chikatetsu","le métro"],
      ["まつり","matsuri","le festival"],
      ["にほん","nihon","le Japon"],
      ["とけい","toke{i}","la montre"],
      ["にわとり","niwatori","la poule"],
      ["ひこうき","hiko{u}ki","l'avion"],
      ["さかな","sakana","le poisson"],
      ["きって","kitte","le timbre"],
      ["おちゃ","ocha","le thé"],
      ["きもの","kimono","le kimono"],
      ["はなし","hanashi","l'histoire"],
      ["あさひ","asahi","le soleil levant"],
      ["てんき","tenki","le temps qu'il fait"],
      ["おんせん","onsen","les bains thermaux"]
    ],
    niveau4: [
      ["みず","mizu","l'eau"],
      ["かぎ","kagi","la clé"],
      ["たび","tabi","le voyage"],
      ["そば","soba","les nouilles soba"],
      ["たまご","tamago","l'œuf"],
      ["てがみ","tegami","la lettre"],
      ["ともだち","tomodachi","l'ami"],
      ["はなび","hanabi","le feu d'artifice"],
      ["でんわ","denwa","le téléphone"],
      ["しごと","shigoto","le travail"],
      ["かばん","kaban","le sac"],
      ["ゆびわ","yubiwa","la bague"],
      ["みどり","midori","le vert"],
      ["ことば","kotoba","le mot"],
      ["がっこう","gakko{u}","l'école"],
      ["くだもの","kudamono","les fruits"],
      ["たべもの","tabemono","la nourriture"]
    ]
  },

  kata: {
    nom: "Katakana",
    yoon: [
      ["キャ","kya"],
      ["キュ","kyu"],
      ["キョ","kyo"],
      ["シャ","sha"],
      ["シュ","shu"],
      ["ショ","sho"],
      ["チャ","cha"],
      ["チュ","chu"],
      ["チョ","cho"],
      ["ニャ","nya"],
      ["ニュ","nyu"],
      ["ニョ","nyo"],
      ["ヒャ","hya"],
      ["ヒュ","hyu"],
      ["ヒョ","hyo"],
      ["ミャ","mya"],
      ["ミュ","myu"],
      ["ミョ","myo"],
      ["リャ","rya"],
      ["リュ","ryu"],
      ["リョ","ryo"],
      ["ギャ","gya"],
      ["ギュ","gyu"],
      ["ギョ","gyo"],
      ["ジャ","ja"],
      ["ジュ","ju"],
      ["ジョ","jo"],
      ["ビャ","bya"],
      ["ビュ","byu"],
      ["ビョ","byo"],
      ["ピャ","pya"],
      ["ピュ","pyu"],
      ["ピョ","pyo"]
    ],
    base: [
      ["ア","a"],
      ["イ","i"],
      ["ウ","u"],
      ["エ","e"],
      ["オ","o"],
      ["カ","ka"],
      ["キ","ki"],
      ["ク","ku"],
      ["ケ","ke"],
      ["コ","ko"],
      ["サ","sa"],
      ["シ","shi"],
      ["ス","su"],
      ["セ","se"],
      ["ソ","so"],
      ["タ","ta"],
      ["チ","chi"],
      ["ツ","tsu"],
      ["テ","te"],
      ["ト","to"],
      ["ナ","na"],
      ["ニ","ni"],
      ["ヌ","nu"],
      ["ネ","ne"],
      ["ノ","no"],
      ["ハ","ha"],
      ["ヒ","hi"],
      ["フ","fu"],
      ["ヘ","he"],
      ["ホ","ho"],
      ["マ","ma"],
      ["ミ","mi"],
      ["ム","mu"],
      ["メ","me"],
      ["モ","mo"],
      ["ヤ","ya"],
      ["ユ","yu"],
      ["ヨ","yo"],
      ["ラ","ra"],
      ["リ","ri"],
      ["ル","ru"],
      ["レ","re"],
      ["ロ","ro"],
      ["ワ","wa"],
      ["ヲ","wo"],
      ["ン","n"]
    ],
    dakuten: [
      ["ガ","ga"],
      ["ギ","gi"],
      ["グ","gu"],
      ["ゲ","ge"],
      ["ゴ","go"],
      ["ザ","za"],
      ["ジ","ji"],
      ["ズ","zu"],
      ["ゼ","ze"],
      ["ゾ","zo"],
      ["ダ","da"],
      ["ヂ","ji"],
      ["ヅ","zu"],
      ["デ","de"],
      ["ド","do"],
      ["バ","ba"],
      ["ビ","bi"],
      ["ブ","bu"],
      ["ベ","be"],
      ["ボ","bo"],
      ["パ","pa"],
      ["ピ","pi"],
      ["プ","pu"],
      ["ペ","pe"],
      ["ポ","po"]
    ],
    niveau2: [
      ["メモ","memo","la note"],
      ["ハム","hamu","le jambon"],
      ["キー","kii","la clé"],
      ["タイ","tai","la Thaïlande"],
      ["ケア","kea","les soins"],
      ["ツナ","tsuna","le thon"],
      ["キロ","kiro","le kilo"],
      ["トン","ton","la tonne"],
      ["ソロ","soro","le solo"],
      ["リス","risu","l'écureuil"],
      ["ワン","wan","un (one)"]
    ],
    niveau3: [
      ["ココア","kokoa","le cacao"],
      ["マイク","maiku","le micro"],
      ["ホテル","hoteru","l'hôtel"],
      ["カメラ","kamera","l'appareil photo"],
      ["トイレ","toire","les toilettes"],
      ["ノート","nooto","le cahier"],
      ["カレー","karee","le curry"],
      ["レモン","remon","le citron"],
      ["メロン","meron","le melon"],
      ["テニス","tenisu","le tennis"],
      ["ミルク","miruku","le lait"],
      ["テスト","tesuto","le test"],
      ["コート","kooto","le manteau"],
      ["タオル","taoru","la serviette"],
      ["ランチ","ranchi","le déjeuner"],
      ["トマト","tomato","la tomate"],
      ["ライス","raisu","le riz"],
      ["コース","koosu","le parcours"],
      ["ケーキ","keeki","le gâteau"],
      ["アイス","aisu","la glace"],
      ["ソース","soosu","la sauce"],
      ["ワイン","wain","le vin"],
      ["レストラン","resutoran","le restaurant"],
      ["ホーム","hoomu","le quai"],
      ["コーヒー","koohii","le café"],
      ["タクシー","takushii","le taxi"],
      ["フランス","furansu","la France"],
      ["チケット","chiketto","le ticket"],
      ["シャワー","shawaa","la douche"],
      ["メニュー","menyuu","le menu"],
      ["ソフト","sofuto","le logiciel"]
    ],
    niveau4: [
      ["パン","pan","le pain"],
      ["ペン","pen","le stylo"],
      ["バス","basu","le bus"],
      ["ドア","doa","la porte"],
      ["ビル","biru","l'immeuble"],
      ["ガム","gamu","le chewing-gum"],
      ["ジム","jimu","la salle de sport"],
      ["ゴム","gomu","le caoutchouc"],
      ["ピザ","piza","la pizza"],
      ["テレビ","terebi","la télévision"],
      ["ビール","biiru","la bière"],
      ["チーズ","chiizu","le fromage"],
      ["ピアノ","piano","le piano"],
      ["スーパー","suupaa","le supermarché"],
      ["カード","kaado","la carte"],
      ["サラダ","sarada","la salade"],
      ["バナナ","banana","la banane"],
      ["ジュース","juusu","le jus"],
      ["パスタ","pasuta","les pâtes"],
      ["ズボン","zubon","le pantalon"],
      ["コピー","kopii","la copie"]
    ]
  }
};
