/* =========================================================================
   VOCABULAIRE — c'est le seul fichier à modifier pour ajouter des mots.

   Chaque ligne a la forme :

     ["rubrique", "emoji", "français", "japonais", "romaji", ["autres formes"]],

   - rubrique : une des clés de RUBRIQUES ci-dessous (politesse, transport,
     direction, resto, achats, hotel, secours, temps, chiffres)
   - emoji    : l'image de la carte, copiée-collée depuis le clavier emoji
   - français : ce qui s'affiche sous l'image
   - japonais : la phrase telle qu'elle s'écrit, kanji compris
   - romaji   : la prononciation, acceptée aussi si tu la tapes
   - autres formes : FACULTATIF. La version tout en kana quand la phrase
     contient des kanji, pour que la reconnaissance vocale accepte les deux.
     Si la phrase est déjà sans kanji, on peut supprimer cette partie.

   Ne pas oublier la virgule en fin de ligne, et garder les guillemets.
   ========================================================================= */

const RUBRIQUES = {
  politesse:{label:"Politesse", kanji:"礼"},
  transport:{label:"Transports", kanji:"駅"},
  direction:{label:"Se repérer", kanji:"道"},
  resto:{label:"Au restaurant", kanji:"食"},
  achats:{label:"Achats", kanji:"買"},
  hotel:{label:"Hôtel & bains", kanji:"泊"},
  services:{label:"Services pratiques", kanji:"便"},
  culture:{label:"Temples & culture", kanji:"寺"},
  secours:{label:"Pépins & santé", kanji:"助"},
  temps:{label:"Temps & horaires", kanji:"時"},
  chiffres:{label:"Chiffres", kanji:"数"}
};

const MOTS = [

  /* ---------- POLITESSE (28) ---------- */
  ["politesse","🌅","Bonjour (matin)","おはようございます","ohayō gozaimasu"],
  ["politesse","🙇‍♀️","Bonjour (journée)","こんにちは","konnichiwa"],
  ["politesse","🌙","Bonsoir","こんばんは","konbanwa"],
  ["politesse","🙏","Merci beaucoup","ありがとうございます","arigatō gozaimasu"],
  ["politesse","✋","Excusez-moi / pardon","すみません","sumimasen"],
  ["politesse","😔","Je suis désolée","ごめんなさい","gomennasai"],
  ["politesse","🤲","S'il vous plaît","お願いします","onegaishimasu",["おねがいします"]],
  ["politesse","❓","Je ne comprends pas","わかりません","wakarimasen"],
  ["politesse","🤝","Enchantée","はじめまして","hajimemashite"],
  ["politesse","🇬🇧","Parlez-vous anglais ?","英語を話せますか","eigo o hanasemasu ka",["えいごをはなせますか"]],
  ["politesse","🗣️","Je parle un peu japonais","日本語が少し話せます","nihongo ga sukoshi hanasemasu",["にほんごがすこしはなせます"]],
  ["politesse","🐢","Plus lentement, s'il vous plaît","ゆっくりお願いします","yukkuri onegaishimasu",["ゆっくりおねがいします"]],
  ["politesse","🔁","Encore une fois, s'il vous plaît","もう一度お願いします","mō ichido onegaishimasu",["もういちどおねがいします"]],
  ["politesse","⏳","Un instant, s'il vous plaît","ちょっと待ってください","chotto matte kudasai",["ちょっとまってください"]],
  ["politesse","📷","Je peux prendre une photo ?","写真を撮ってもいいですか","shashin o totte mo ii desu ka",["しゃしんをとってもいいですか"]],
  ["politesse","👌","Ça va, c'est bon","大丈夫です","daijōbu desu",["だいじょうぶです"]],
  ["politesse","🙅‍♀️","Non merci","けっこうです","kekkō desu"],
  ["politesse","👋","Au revoir","さようなら","sayōnara"],
  ["politesse","🪪","Comment vous appelez-vous ?","名前は何ですか","namae wa nan desu ka",["なまえはなんですか"]],
  ["politesse","🇫🇷","Je suis française","フランス人です","furansujin desu",["ふらんすじんです"]],
  ["politesse","🛬","Je viens de France","フランスから来ました","furansu kara kimashita",["ふらんすからきました"]],
  ["politesse","🏖️","Je suis en voyage","旅行で来ました","ryokō de kimashita",["りょこうできました"]],
  ["politesse","✔️","Oui","はい","hai"],
  ["politesse","✖️","Non","いいえ","iie"],
  ["politesse","💡","J'ai compris","わかりました","wakarimashita"],
  ["politesse","🤷‍♀️","Je ne sais pas","知りません","shirimasen",["しりません"]],
  ["politesse","😊","C'était très agréable","楽しかったです","tanoshikatta desu",["たのしかったです"]],
  ["politesse","🔜","Je reviendrai","また来ます","mata kimasu",["またきます"]],

  /* ---------- TRANSPORTS (27) ---------- */
  ["transport","🚉","La gare","駅","eki",["えき"]],
  ["transport","🚃","Le train","電車","densha",["でんしゃ"]],
  ["transport","🚄","Le shinkansen","新幹線","shinkansen",["しんかんせん"]],
  ["transport","🚇","Le métro","地下鉄","chikatetsu",["ちかてつ"]],
  ["transport","🚌","Le bus","バス","basu"],
  ["transport","🚕","Le taxi","タクシー","takushī"],
  ["transport","🎫","Le billet","切符","kippu",["きっぷ"]],
  ["transport","✈️","L'aéroport","空港","kūkō",["くうこう"]],
  ["transport","🚪","La sortie","出口","deguchi",["でぐち"]],
  ["transport","📍","Je voudrais aller ici","ここに行きたいです","koko ni ikitai desu",["ここにいきたいです"]],
  ["transport","🔀","La correspondance","乗り換え","norikae",["のりかえ"]],
  ["transport","🛤️","C'est quelle voie ?","何番線ですか","nanbansen desu ka",["なんばんせんですか"]],
  ["transport","➡️","Aller simple","片道","katamichi",["かたみち"]],
  ["transport","🔄","Aller-retour","往復","ōfuku",["おうふく"]],
  ["transport","💺","Place réservée","指定席","shiteiseki",["していせき"]],
  ["transport","🪑","Place libre","自由席","jiyūseki",["じゆうせき"]],
  ["transport","⏭️","Le prochain train","次の電車","tsugi no densha",["つぎのでんしゃ"]],
  ["transport","🌃","Le dernier train est à quelle heure ?","終電は何時ですか","shūden wa nanji desu ka",["しゅうでんはなんじですか"]],
  ["transport","🐢","Le train a du retard","電車が遅れています","densha ga okurete imasu",["でんしゃがおくれています"]],
  ["transport","🚲","Le vélo","自転車","jitensha",["じてんしゃ"]],
  ["transport","🚗","La voiture de location","レンタカー","rentakā"],
  ["transport","⛴️","Le ferry","フェリー","ferī"],
  ["transport","⚓","Le port","港","minato",["みなと"]],
  ["transport","🚏","L'arrêt de bus","バス停","basutei",["ばすてい"]],
  ["transport","🕒","Les horaires","時刻表","jikokuhyō",["じこくひょう"]],
  ["transport","😣","C'est bondé","満員です","man'in desu",["まんいんです"]],
  ["transport","🛑","Je descends ici","ここで降ります","koko de orimasu",["ここでおります"]],

  /* ---------- SE REPÉRER (12) ---------- */
  ["direction","🗺️","C'est où ?","どこですか","doko desu ka"],
  ["direction","🚻","Où sont les toilettes ?","トイレはどこですか","toire wa doko desu ka",["といれはどこですか"]],
  ["direction","📌","Où suis-je ?","ここはどこですか","koko wa doko desu ka"],
  ["direction","➡️","À droite","右","migi",["みぎ"]],
  ["direction","⬅️","À gauche","左","hidari",["ひだり"]],
  ["direction","⬆️","Tout droit","まっすぐ","massugu"],
  ["direction","🚶‍♀️","C'est loin ?","遠いですか","tōi desu ka",["とおいですか"]],
  ["direction","⏱️","C'est à combien de minutes à pied ?","歩いて何分ですか","aruite nanpun desu ka",["あるいてなんぷんですか"]],
  ["direction","🏪","Y a-t-il un konbini près d'ici ?","近くにコンビニはありますか","chikaku ni konbini wa arimasu ka",["ちかくにこんびにはありますか"]],
  ["direction","ℹ️","Le bureau d'information","案内所","annaijo",["あんないじょ"]],
  ["direction","🧭","Je suis perdue","道に迷いました","michi ni mayoimashita",["みちにまよいました"]],
  ["direction","🗾","Une carte, s'il vous plaît","地図をください","chizu o kudasai",["ちずをください"]],

  /* ---------- AU RESTAURANT (33) ---------- */
  ["resto","📖","Le menu, s'il vous plaît","メニューをお願いします","menyū o onegaishimasu",["めにゅーをおねがいします"]],
  ["resto","1️⃣","Une personne","一人です","hitori desu",["ひとりです"]],
  ["resto","2️⃣","Deux personnes","二人です","futari desu",["ふたりです"]],
  ["resto","👉","Celui-ci, s'il vous plaît","これをください","kore o kudasai"],
  ["resto","🤔","Qu'est-ce que c'est ?","これは何ですか","kore wa nan desu ka",["これはなんですか"]],
  ["resto","⭐","Qu'est-ce que vous recommandez ?","おすすめは何ですか","osusume wa nan desu ka",["おすすめはなんですか"]],
  ["resto","💧","De l'eau","お水","omizu",["おみず"]],
  ["resto","🍵","Du thé","お茶","ocha",["おちゃ"]],
  ["resto","🍺","Une bière","ビール","bīru"],
  ["resto","🥢","Les baguettes","お箸","ohashi",["おはし"]],
  ["resto","🌶️","C'est épicé ?","辛いですか","karai desu ka",["からいですか"]],
  ["resto","😋","C'est délicieux","おいしいです","oishii desu"],
  ["resto","🥗","Je suis végétarienne","ベジタリアンです","bejitarian desu"],
  ["resto","🥩","La viande","肉","niku",["にく"]],
  ["resto","🐟","Le poisson","魚","sakana",["さかな"]],
  ["resto","🍤","Les crevettes","エビ","ebi"],
  ["resto","🥚","L'œuf","卵","tamago",["たまご"]],
  ["resto","🐷","Je ne mange pas de porc","豚肉が食べられません","butaniku ga taberaremasen",["ぶたにくがたべられません"]],
  ["resto","🥡","C'est possible à emporter ?","テイクアウトできますか","teikuauto dekimasu ka",["ているあうとできますか"]],
  ["resto","🧾","L'addition, s'il vous plaît","お会計お願いします","okaikei onegaishimasu",["おかいけいおねがいします"]],
  ["resto","🙏","Avant de manger","いただきます","itadakimasu"],
  ["resto","🍚","Après le repas","ごちそうさまでした","gochisōsama deshita"],
  ["resto","🍣","Les sushis","寿司","sushi",["すし"]],
  ["resto","🍜","Les ramen","ラーメン","rāmen"],
  ["resto","🥘","Les tempuras","天ぷら","tenpura",["てんぷら"]],
  ["resto","🍱","Le menu complet","定食","teishoku",["ていしょく"]],
  ["resto","🌾","Le riz","ご飯","gohan",["ごはん"]],
  ["resto","🥬","Les légumes","野菜","yasai",["やさい"]],
  ["resto","🍎","Les fruits","果物","kudamono",["くだもの"]],
  ["resto","🍬","C'est sucré","甘いです","amai desu",["あまいです"]],
  ["resto","🍽️","Vous avez une table ?","席はありますか","seki wa arimasu ka",["せきはありますか"]],
  ["resto","❌","Je n'ai pas réservé","予約していません","yoyaku shite imasen",["よやくしていません"]],
  ["resto","➕","Je peux en reprendre ?","おかわりできますか","okawari dekimasu ka"],

  /* ---------- ACHATS (16) ---------- */
  ["achats","💴","C'est combien ?","いくらですか","ikura desu ka"],
  ["achats","💳","Je peux payer par carte ?","カードで払えますか","kādo de haraemasu ka",["かーどではらえますか"]],
  ["achats","💵","Les espèces","現金","genkin",["げんきん"]],
  ["achats","😮","C'est cher","高いです","takai desu",["たかいです"]],
  ["achats","🛍️","Un sac, s'il vous plaît","袋をください","fukuro o kudasai",["ふくろをください"]],
  ["achats","👀","Je regarde seulement","見ているだけです","mite iru dake desu",["みているだけです"]],
  ["achats","👗","Je peux l'essayer ?","試着してもいいですか","shichaku shite mo ii desu ka",["しちゃくしてもいいですか"]],
  ["achats","📏","Vous avez une autre taille ?","他のサイズはありますか","hoka no saizu wa arimasu ka",["ほかのさいずはありますか"]],
  ["achats","🧳","La détaxe est possible ?","免税できますか","menzei dekimasu ka",["めんぜいできますか"]],
  ["achats","🧻","Le reçu","レシート","reshīto"],
  ["achats","🏪","Le konbini","コンビニ","konbini"],
  ["achats","🎁","Le souvenir à offrir","お土産","omiyage",["おみやげ"]],
  ["achats","🏷️","C'est bon marché","安いです","yasui desu",["やすいです"]],
  ["achats","🔖","Il y a une réduction ?","割引はありますか","waribiki wa arimasu ka",["わりびきはありますか"]],
  ["achats","🐘","C'est grand","大きいです","ōkii desu",["おおきいです"]],
  ["achats","🐁","C'est petit","小さいです","chiisai desu",["ちいさいです"]],

  /* ---------- HÔTEL & BAINS (18) ---------- */
  ["hotel","🏨","L'hôtel","ホテル","hoteru"],
  ["hotel","📝","J'ai une réservation","予約しています","yoyaku shite imasu",["よやくしています"]],
  ["hotel","🚪","La chambre","部屋","heya",["へや"]],
  ["hotel","🔑","La clé","鍵","kagi",["かぎ"]],
  ["hotel","🧳","Les bagages","荷物","nimotsu",["にもつ"]],
  ["hotel","🛅","Vous pouvez garder mes bagages ?","荷物を預かってもらえますか","nimotsu o azukatte moraemasu ka",["にもつをあずかってもらえますか"]],
  ["hotel","📶","Il y a le wifi ?","Wi-Fiはありますか","waifai wa arimasu ka",["わいふぁいはありますか"]],
  ["hotel","🧼","Une serviette","タオル","taoru"],
  ["hotel","❄️","La climatisation","エアコン","eakon"],
  ["hotel","🥶","La chambre est froide","部屋が寒いです","heya ga samui desu",["へやがさむいです"]],
  ["hotel","⏰","À quelle heure le petit-déjeuner ?","朝ごはんは何時ですか","asagohan wa nanji desu ka",["あさごはんはなんじですか"]],
  ["hotel","🕚","À quelle heure le départ ?","チェックアウトは何時ですか","chekkuauto wa nanji desu ka",["ちぇっくあうとはなんじですか"]],
  ["hotel","♨️","Les bains thermaux","温泉","onsen",["おんせん"]],
  ["hotel","🩱","Je peux entrer avec un tatouage ?","タトゥーがあっても入れますか","tatū ga atte mo hairemasu ka",["たとぅーがあってもはいれますか"]],
  ["hotel","🏮","La chambre japonaise","和室","washitsu",["わしつ"]],
  ["hotel","🛏️","Le futon","布団","futon",["ふとん"]],
  ["hotel","👘","Le yukata","浴衣","yukata",["ゆかた"]],
  ["hotel","🧹","Vous pouvez faire le ménage ?","掃除してください","sōji shite kudasai",["そうじしてください"]],

  /* ---------- SERVICES PRATIQUES (13) ---------- */
  ["services","📮","La poste","郵便局","yūbinkyoku",["ゆうびんきょく"]],
  ["services","🏧","Où y a-t-il un distributeur ?","ATMはどこですか","ATM wa doko desu ka",["えーてぃーえむはどこですか"]],
  ["services","💱","Je peux changer de l'argent ?","両替できますか","ryōgae dekimasu ka",["りょうがえできますか"]],
  ["services","🔐","Le casier à bagages","コインロッカー","koinrokkā"],
  ["services","📦","L'envoi de bagages","宅配便","takuhaibin",["たくはいびん"]],
  ["services","🧺","La laverie automatique","コインランドリー","koinrandorī"],
  ["services","🔌","Je peux recharger mon téléphone ?","充電できますか","jūden dekimasu ka",["じゅうでんできますか"]],
  ["services","📱","Vous avez des cartes SIM ?","SIMカードはありますか","SIM kādo wa arimasu ka",["しむかーどはありますか"]],
  ["services","🚓","Le poste de police de quartier","交番","kōban",["こうばん"]],
  ["services","🗑️","La poubelle","ゴミ箱","gomibako",["ごみばこ"]],
  ["services","🤝","Vous pouvez m'aider ?","手伝ってもらえますか","tetsudatte moraemasu ka",["てつだってもらえますか"]],
  ["services","☂️","Le parapluie","傘","kasa",["かさ"]],
  ["services","🚭","L'espace fumeurs","喫煙所","kitsuenjo",["きつえんじょ"]],

  /* ---------- TEMPLES & CULTURE (15) ---------- */
  ["culture","⛩️","Le sanctuaire shinto","神社","jinja",["じんじゃ"]],
  ["culture","🛕","Le temple bouddhiste","お寺","otera",["おてら"]],
  ["culture","🏯","Le château","お城","oshiro",["おしろ"]],
  ["culture","🌿","Le jardin","庭園","teien",["ていえん"]],
  ["culture","🖼️","Le musée d'art","美術館","bijutsukan",["びじゅつかん"]],
  ["culture","🏛️","Le musée","博物館","hakubutsukan",["はくぶつかん"]],
  ["culture","🎟️","C'est combien l'entrée ?","入場料はいくらですか","nyūjōryō wa ikura desu ka",["にゅうじょうりょうはいくらですか"]],
  ["culture","📵","Les photos sont interdites ?","写真はだめですか","shashin wa dame desu ka",["しゃしんはだめですか"]],
  ["culture","👟","Faut-il se déchausser ?","靴を脱ぎますか","kutsu o nugimasu ka",["くつをぬぎますか"]],
  ["culture","🧿","L'amulette porte-bonheur","お守り","omamori",["おまもり"]],
  ["culture","🖋️","Le sceau de pèlerin","御朱印","goshuin",["ごしゅいん"]],
  ["culture","🌸","Les cerisiers en fleurs","花見","hanami",["はなみ"]],
  ["culture","🍁","Les érables d'automne","紅葉","kōyō",["こうよう"]],
  ["culture","🎏","Le festival","祭り","matsuri",["まつり"]],
  ["culture","🎋","C'est magnifique","きれいですね","kirei desu ne"],

  /* ---------- PÉPINS & SANTÉ (16) ---------- */
  ["secours","🆘","Au secours !","助けて","tasukete",["たすけて"]],
  ["secours","🏥","L'hôpital","病院","byōin",["びょういん"]],
  ["secours","👮","La police","警察","keisatsu",["けいさつ"]],
  ["secours","💊","La pharmacie","薬局","yakkyoku",["やっきょく"]],
  ["secours","🚑","Appelez une ambulance","救急車を呼んでください","kyūkyūsha o yonde kudasai",["きゅうきゅうしゃをよんでください"]],
  ["secours","👨‍⚕️","Appelez un médecin","医者を呼んでください","isha o yonde kudasai",["いしゃをよんでください"]],
  ["secours","🤒","Je ne me sens pas bien","気分が悪いです","kibun ga warui desu",["きぶんがわるいです"]],
  ["secours","🌡️","J'ai de la fièvre","熱があります","netsu ga arimasu",["ねつがあります"]],
  ["secours","🤕","J'ai mal à la tête","頭が痛いです","atama ga itai desu",["あたまがいたいです"]],
  ["secours","😖","J'ai mal au ventre","お腹が痛いです","onaka ga itai desu",["おなかがいたいです"]],
  ["secours","👛","J'ai perdu mon porte-monnaie","財布をなくしました","saifu o nakushimashita",["さいふをなくしました"]],
  ["secours","🎒","J'ai fait tomber quelque chose","落としました","otoshimashita",["おとしました"]],
  ["secours","🛂","Le passeport","パスポート","pasupōto"],
  ["secours","🏛️","L'ambassade","大使館","taishikan",["たいしかん"]],
  ["secours","⚠️","J'ai une allergie","アレルギーがあります","arerugī ga arimasu"],
  ["secours","📄","L'assurance","保険","hoken",["ほけん"]],

  /* ---------- TEMPS & HORAIRES (16) ---------- */
  ["temps","🕐","Il est quelle heure ?","何時ですか","nanji desu ka",["なんじですか"]],
  ["temps","📅","Aujourd'hui","今日","kyō",["きょう"]],
  ["temps","🌅","Demain","明日","ashita",["あした"]],
  ["temps","🌄","Hier","昨日","kinō",["きのう"]],
  ["temps","⏱️","Maintenant","今","ima",["いま"]],
  ["temps","🌤️","Le matin","朝","asa",["あさ"]],
  ["temps","🌆","Le soir","夜","yoru",["よる"]],
  ["temps","🔓","Ça ouvre à quelle heure ?","何時からですか","nanji kara desu ka",["なんじからですか"]],
  ["temps","🔒","Ça ferme à quelle heure ?","何時までですか","nanji made desu ka",["なんじまでですか"]],
  ["temps","🚫","C'est fermé aujourd'hui ?","今日は休みですか","kyō wa yasumi desu ka",["きょうはやすみですか"]],
  ["temps","☀️","Le temps qu'il fait","天気","tenki",["てんき"]],
  ["temps","🌧️","La pluie","雨","ame",["あめ"]],
  ["temps","🥵","Il fait chaud","暑いです","atsui desu",["あついです"]],
  ["temps","🥶","Il fait froid","寒いです","samui desu",["さむいです"]],
  ["temps","🌀","Le typhon","台風","taifū",["たいふう"]],
  ["temps","📆","Le week-end","週末","shūmatsu",["しゅうまつ"]],

  /* ---------- CHIFFRES (13) ---------- */
  ["chiffres","1️⃣","Un","一","ichi",["いち","1","1つ","一つ"]],
  ["chiffres","2️⃣","Deux","二","ni",["に","2","2つ","二つ"]],
  ["chiffres","3️⃣","Trois","三","san",["さん","3","3つ","三つ"]],
  ["chiffres","4️⃣","Quatre","四","yon",["よん","し","4","4つ","四つ"]],
  ["chiffres","5️⃣","Cinq","五","go",["ご","5","5つ","五つ"]],
  ["chiffres","6️⃣","Six","六","roku",["ろく","6","6つ","六つ"]],
  ["chiffres","7️⃣","Sept","七","nana",["なな","しち","7","7つ","七つ"]],
  ["chiffres","8️⃣","Huit","八","hachi",["はち","8","8つ","八つ"]],
  ["chiffres","9️⃣","Neuf","九","kyū",["きゅう","く","9","9つ","九つ"]],
  ["chiffres","🔟","Dix","十","jū",["じゅう","10","１０"]],
  ["chiffres","💯","Cent","百","hyaku",["ひゃく","100","１００"]],
  ["chiffres","🏯","Mille","千","sen",["せん","1000","1,000"]],
  ["chiffres","💴","Le yen","円","en",["えん","円","¥"]]

];
